version: '3.8'

services:
  client:
    container_name: client
    env_file:
      - ../src/client/.env
    build: ../src/client
    ports:
      - '3000:3000'
    restart: always

  postgres:
    image: postgres:14.1-alpine
    container_name: postgresql
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


  server:
    container_name: server
    env_file:
      - ../src/server/.env
    build: ../src/server
    ports:
      - '7000:7000'
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres:
    driver: local
