version: '3.8'

services:
  server:
    container_name: server
    env_file:
      - ../src/server/.env
    build: ../src/server
    ports:
      - 7000:7000
    depends_on:
      - postgres
    restart: always
  client:
    container_name: client
    env_file:
      - ../src/client/.env
    build: ../src/client
    ports:
      - 3000:3000
    restart: always
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
